language: generic 
sudo: required
services:
    docker

before-install:
    - docker build -t rpaiva77/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rpaiva77/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "Docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-983918740930"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
	secret_access_key: $AWS_SECRET_KEY