language: generic 
sudo: required
services:
    docker

before-install:
    - docker build -t rpaiva77/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rpaiva77/docker-react npm run test